spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-laboratory # mysql 모드 설정
    username: mylaboratory
    password: 12341234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true  # 쿼리를 이쁘게 포맷팅
#        use_sql_comments: true # 쿼리가 왜 나왔는지 코멘트
        enable_lazy_load_no_trans: false
        default_batch_fetch_size: 1000

#        dialect: org.hibernate.dialect.MySQLDialect #DB에 전달하는 SQL 형식 지정
#    show-sql: true  # 쿼리를 보여줌
    generate-ddl: true
    defer-datasource-initialization: true
    open-in-view:

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

springdoc:
  packages-to-scan: com.mylaboratory.spring.swagger
  swagger-ui:
    path: /test                   # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: method     # alpha: 알파벳 순 메서드 정렬, method: HTTP Method 순 정렬
  #    enabled: false # swagger-ui를 비활성화하려면 다음 속성을 사용 (swagger-ui 사용하지 않을 경우 설정)
  api-docs:
    path: /api-docs
#    enabled: false  # 엔드포인트(기본적으로 /v3/api-docs)를 비활성화하려면 다음 속성을 사용, swagger-ui 도 비활성화 됨
  cache:
    disabled: true